# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: dactyl_manuform_5x6_dongle
    artifact-name: dactyl_central
  - board: nrfmicro_13
    shield: dactyl_manuform_5x6_left
    artifact-name: dactyl_left
  - board: nrfmicro_13
    shield: dactyl_manuform_5x6_right
    artifact-name: dactyl_right
  - board: nrfmicro_13
    shield: settings_reset
